language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - pip install -e .
  - pip install nose
  - pip install coverage

# command to run tests
script: 
    - nosetests --with-coverage
